spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    queue: customer.queue

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/tu-realm
          # En local (Swagger/Pruebas desde tu máquina)
          jwk-set-uri: http://localhost:8081/realms/customer-realm/protocol/openid-connect/certs

  main:
    allow-bean-definition-overriding: true

logging:
  level:
    root: INFO
    com.company.customerservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

client:
  life-expectancy: 80

---

# PERFIL DEV
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/realms/customer-realm/protocol/openid-connect/certs

---

# PERFIL PROD
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://prod-db-host:5432/customerdb
    username: produser
    password: ProdPassword123

  rabbitmq:
    host: prod-rabbit-host
    port: 5672
    username: prodUser
    password: ProdRabbitPassword123

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://prod-auth-server/realms/customer-realm/protocol/openid-connect/certs
